---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: slave-ingress
  namespace: smi-slave-staging
  labels:
    app: smi-slave-staging
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: smi-slave.dev.lappis.rocks
    http:
      paths:
      - backend:
          serviceName: slave-svc
          servicePort: 80
  tls:
  - hosts:
    - smi-slave.dev.lappis.rocks
    secretName: smi-slave-staging-letsencrypt-prod-crt
---
apiVersion: v1
kind: Service
metadata:
  name: slave-svc
  namespace: smi-slave-staging
  labels:
    app: smi-slave-staging
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: smi-slave-staging
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: slave-deployment
  namespace: smi-slave-staging
  labels:
    app: smi-slave-staging
spec:
  selector:
    matchLabels:
      app: smi-slave-staging
  replicas: 1
  template:
    metadata:
      labels:
        app: smi-slave-staging
    spec:
      containers:
      - name: smi-slave-staging
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        command: ["sh", "scripts/start.sh"]
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: SLAVE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: "slave-staging-secrets"
              key: "app-secret-key"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: "slave-staging-secrets"
              key: "db-user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "slave-staging-secrets"
              key: "db-user-pass"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "smi-slave-dev"
        - name: POSTGRES_HOST
          value: postgres
        - name: ENVIRONMENT
          value: production
        - name: ALLOWED_HOST
          value: smi-slave.dev.lappis.rocks
